# Generated by Django 4.2.2 on 2023-08-17 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisment', '0004_alter_advertisement_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='text',
            new_name='descriptoin',
        ),
        migrations.AlterModelTable(
            name='advertisement',
            table='advertisments',
        ),
    ]
