# Generated by Django 4.2.2 on 2023-08-21 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisment', '0005_rename_text_advertisement_descriptoin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
